# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app_comm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app_comm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61pp_comm.proto\x12\x11\x61pp_communication\"#\n\x0bJSONRequest\x12\x14\n\x0cjson_payload\x18\x01 \x01(\t\"0\n\x0cJSONResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xad\x01\n\x0e\x41ppCommService\x12K\n\x08SendJSON\x12\x1e.app_communication.JSONRequest\x1a\x1f.app_communication.JSONResponse\x12N\n\x0bReceiveJSON\x12\x1e.app_communication.JSONRequest\x1a\x1f.app_communication.JSONResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_comm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JSONREQUEST']._serialized_start=37
  _globals['_JSONREQUEST']._serialized_end=72
  _globals['_JSONRESPONSE']._serialized_start=74
  _globals['_JSONRESPONSE']._serialized_end=122
  _globals['_APPCOMMSERVICE']._serialized_start=125
  _globals['_APPCOMMSERVICE']._serialized_end=298
# @@protoc_insertion_point(module_scope)
