# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hud_stream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hud_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10hud_stream.proto\x12\x03hud\" \n\nHudRequest\x12\x12\n\ntarget_fps\x18\x01 \x01(\r\"$\n\x08HudFrame\x12\x0c\n\x04jpeg\x18\x01 \x01(\x0c\x12\n\n\x02ts\x18\x02 \x01(\x04\x32;\n\nHudService\x12-\n\tStreamHud\x12\x0f.hud.HudRequest\x1a\r.hud.HudFrame0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hud_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HUDREQUEST']._serialized_start=25
  _globals['_HUDREQUEST']._serialized_end=57
  _globals['_HUDFRAME']._serialized_start=59
  _globals['_HUDFRAME']._serialized_end=95
  _globals['_HUDSERVICE']._serialized_start=97
  _globals['_HUDSERVICE']._serialized_end=156
# @@protoc_insertion_point(module_scope)
