# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hud_stream_pb2 as hud__stream__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hud_stream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HudServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamHud = channel.unary_stream(
                '/hud.HudService/StreamHud',
                request_serializer=hud__stream__pb2.HudRequest.SerializeToString,
                response_deserializer=hud__stream__pb2.HudFrame.FromString,
                _registered_method=True)


class HudServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamHud(self, request, context):
        """클라이언트가 요청하면 서버가 연속으로 HudFrame을 전송(서버 스트리밍)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HudServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamHud': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamHud,
                    request_deserializer=hud__stream__pb2.HudRequest.FromString,
                    response_serializer=hud__stream__pb2.HudFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hud.HudService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hud.HudService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HudService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamHud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hud.HudService/StreamHud',
            hud__stream__pb2.HudRequest.SerializeToString,
            hud__stream__pb2.HudFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
